// +build !ignore_autogenerated

/*
Copyright 2019 The Kubedge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedgeClusterProviderSpec) DeepCopyInto(out *KubedgeClusterProviderSpec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedgeClusterProviderSpec.
func (in *KubedgeClusterProviderSpec) DeepCopy() *KubedgeClusterProviderSpec {
	if in == nil {
		return nil
	}
	out := new(KubedgeClusterProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedgeClusterProviderSpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedgeClusterProviderSpecList) DeepCopyInto(out *KubedgeClusterProviderSpecList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubedgeClusterProviderSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedgeClusterProviderSpecList.
func (in *KubedgeClusterProviderSpecList) DeepCopy() *KubedgeClusterProviderSpecList {
	if in == nil {
		return nil
	}
	out := new(KubedgeClusterProviderSpecList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedgeClusterProviderSpecList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedgeClusterProviderSpecSpec) DeepCopyInto(out *KubedgeClusterProviderSpecSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedgeClusterProviderSpecSpec.
func (in *KubedgeClusterProviderSpecSpec) DeepCopy() *KubedgeClusterProviderSpecSpec {
	if in == nil {
		return nil
	}
	out := new(KubedgeClusterProviderSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedgeClusterProviderSpecStatus) DeepCopyInto(out *KubedgeClusterProviderSpecStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedgeClusterProviderSpecStatus.
func (in *KubedgeClusterProviderSpecStatus) DeepCopy() *KubedgeClusterProviderSpecStatus {
	if in == nil {
		return nil
	}
	out := new(KubedgeClusterProviderSpecStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedgeClusterProviderStatus) DeepCopyInto(out *KubedgeClusterProviderStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedgeClusterProviderStatus.
func (in *KubedgeClusterProviderStatus) DeepCopy() *KubedgeClusterProviderStatus {
	if in == nil {
		return nil
	}
	out := new(KubedgeClusterProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedgeClusterProviderStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedgeClusterProviderStatusList) DeepCopyInto(out *KubedgeClusterProviderStatusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubedgeClusterProviderStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedgeClusterProviderStatusList.
func (in *KubedgeClusterProviderStatusList) DeepCopy() *KubedgeClusterProviderStatusList {
	if in == nil {
		return nil
	}
	out := new(KubedgeClusterProviderStatusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedgeClusterProviderStatusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedgeClusterProviderStatusSpec) DeepCopyInto(out *KubedgeClusterProviderStatusSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedgeClusterProviderStatusSpec.
func (in *KubedgeClusterProviderStatusSpec) DeepCopy() *KubedgeClusterProviderStatusSpec {
	if in == nil {
		return nil
	}
	out := new(KubedgeClusterProviderStatusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedgeClusterProviderStatusStatus) DeepCopyInto(out *KubedgeClusterProviderStatusStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedgeClusterProviderStatusStatus.
func (in *KubedgeClusterProviderStatusStatus) DeepCopy() *KubedgeClusterProviderStatusStatus {
	if in == nil {
		return nil
	}
	out := new(KubedgeClusterProviderStatusStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedgeMachineProviderSpec) DeepCopyInto(out *KubedgeMachineProviderSpec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedgeMachineProviderSpec.
func (in *KubedgeMachineProviderSpec) DeepCopy() *KubedgeMachineProviderSpec {
	if in == nil {
		return nil
	}
	out := new(KubedgeMachineProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedgeMachineProviderSpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedgeMachineProviderSpecList) DeepCopyInto(out *KubedgeMachineProviderSpecList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubedgeMachineProviderSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedgeMachineProviderSpecList.
func (in *KubedgeMachineProviderSpecList) DeepCopy() *KubedgeMachineProviderSpecList {
	if in == nil {
		return nil
	}
	out := new(KubedgeMachineProviderSpecList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedgeMachineProviderSpecList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedgeMachineProviderSpecSpec) DeepCopyInto(out *KubedgeMachineProviderSpecSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedgeMachineProviderSpecSpec.
func (in *KubedgeMachineProviderSpecSpec) DeepCopy() *KubedgeMachineProviderSpecSpec {
	if in == nil {
		return nil
	}
	out := new(KubedgeMachineProviderSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedgeMachineProviderSpecStatus) DeepCopyInto(out *KubedgeMachineProviderSpecStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedgeMachineProviderSpecStatus.
func (in *KubedgeMachineProviderSpecStatus) DeepCopy() *KubedgeMachineProviderSpecStatus {
	if in == nil {
		return nil
	}
	out := new(KubedgeMachineProviderSpecStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedgeMachineProviderStatus) DeepCopyInto(out *KubedgeMachineProviderStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedgeMachineProviderStatus.
func (in *KubedgeMachineProviderStatus) DeepCopy() *KubedgeMachineProviderStatus {
	if in == nil {
		return nil
	}
	out := new(KubedgeMachineProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedgeMachineProviderStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedgeMachineProviderStatusList) DeepCopyInto(out *KubedgeMachineProviderStatusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubedgeMachineProviderStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedgeMachineProviderStatusList.
func (in *KubedgeMachineProviderStatusList) DeepCopy() *KubedgeMachineProviderStatusList {
	if in == nil {
		return nil
	}
	out := new(KubedgeMachineProviderStatusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubedgeMachineProviderStatusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedgeMachineProviderStatusSpec) DeepCopyInto(out *KubedgeMachineProviderStatusSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedgeMachineProviderStatusSpec.
func (in *KubedgeMachineProviderStatusSpec) DeepCopy() *KubedgeMachineProviderStatusSpec {
	if in == nil {
		return nil
	}
	out := new(KubedgeMachineProviderStatusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubedgeMachineProviderStatusStatus) DeepCopyInto(out *KubedgeMachineProviderStatusStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubedgeMachineProviderStatusStatus.
func (in *KubedgeMachineProviderStatusStatus) DeepCopy() *KubedgeMachineProviderStatusStatus {
	if in == nil {
		return nil
	}
	out := new(KubedgeMachineProviderStatusStatus)
	in.DeepCopyInto(out)
	return out
}
